export const EMAIL_CHANGED ='EMAIL_CHANGED';
export const PASSWORD_CHANGED ='PASSWORD_CHANGED';
export const USER_LOGIN_ATTEMP ='USER_LOGIN_ATTEMP';
export const USER_LOGIN_SUCCESS ='USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL =' USER_LOGIN_FAIL';

// ..........register.....................
export const MOBAIL_REGISTER_CHENGED ='MOBAIL_ REGISTER_CHENGED';
export const PASSWORD_REGISTER_CHANGED =' PASSWORD_REGISTER_CHANGED';
export const USER_REGISTER_ATTEMP ='USER_REGISTER_ATTEMP';
export const USER_REGISTER_SUCCESS ='USER_REGISTER_SUCCESS';